### ISSUE TITLE
How to undone lazy-loaded

### ISSUE THREAD

**Issue by Yousuf28** [hlissner/emacs-company-dict#13]
### What would you like to know?

Let's Say I have very small list of words. And I want immediate completion when typing first  2 character. Is there any way to make this as not lazy-loaded.

**Comment by hlissner** [comment]
Sounds like the `company-idle-delay` or `company-minimum-prefix-length` settings are what you're looking for. Please refer to [the company-mode docs](http://company-mode.github.io/manual/Customization.html#Customization) on how to customize these two settings.
