### ISSUE TITLE
can company-dict integrated to company-complete?

### ISSUE THREAD

**Issue by ziyouchutuwenwu** [hlissner/emacs-company-dict#7]
now i should type company-dict to popup words listed from my custom dict( or bind with keys)
is there a way that i just type company-complete instead of typing company-dict?

**Comment by hlissner** [comment]
Whoa, so sorry for the really late reply. Yes, you can do this by adding `company-dict` to `company-backends`, like so:

```elisp
(add-to-list 'company-backends 'company-dict)
```
